import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowDown, ArrowRight, BookOpen, FileText } from "lucide-react";
import glassDossier from "@/assets/glass-dossier.jpg";
import dossierAsset from "@/assets/onderzoeksdossier.pdf.asset.json";
import { SiteShell, StatusBadge } from "@/components/site-shell";
import { chapters, claims } from "@/lib/dossier-data";

export const Route = createFileRoute("/")({head:()=>({meta:[{title:"Achter het profiel — Onderzoek naar digitale intimiteit"},{name:"description",content:"Een controleerbaar dossier over de commerciële infrastructuur achter betaalde digitale intimiteit."},{property:"og:title",content:"Achter het profiel"},{property:"og:description",content:"Wie praat er, welke data beweegt mee en wie heeft de controle?"},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:HomePage});

function HomePage(){return <SiteShell><main>
  <section className="home-hero"><img src={glassDossier} alt="Abstracte glazen lagen als metafoor voor onzichtbare digitale infrastructuur"/><div className="hero-shade"/><div className="hero-content"><p className="eyebrow">Onderzoeksdossier · editie 01</p><h1>Achter het<br/><em>profiel</em></h1><p className="hero-deck">Wie praat er werkelijk, welke data beweegt mee en wie heeft de controle over digitale intimiteit?</p><div className="hero-actions"><Link to="/hoofdstuk/$slug" params={{slug:"markt-achter-het-profiel"}} className="primary-action"><BookOpen size={17}/>Lees online</Link><a href={dossierAsset.url} target="_blank" rel="noreferrer" className="secondary-action"><FileText size={17}/>Open publicatie</a></div></div><a href="#samenvatting" className="scroll-cue"><ArrowDown size={16}/>Scroll naar het onderzoek</a></section>
  <section id="samenvatting" className="summary-band"><div className="section-inner"><div><p className="eyebrow text-alert">De onderzoeksvraag</p><h2>Intimiteit is persoonlijk.<br/>De infrastructuur erachter is dat niet.</h2></div><div><p>Betaalde gesprekken kunnen worden ondersteund door managers, chatteams, klantsoftware en automatisering. Dat is deels goed gedocumenteerd. Maar de zwaarste conclusies vragen meer bewijs dan publieke bronnen nu bieden.</p><div className="summary-facts"><span><strong>06</strong> hoofdstukken</span><span><strong>06</strong> getoetste claims</span><span><strong>07</strong> kernbronnen</span></div></div></div></section>
  <section className="chapters-section"><div className="section-heading"><p className="eyebrow">Het dossier</p><h2>Zes lagen van één systeem</h2><p>Lees lineair, of begin bij de vraag die u wilt controleren.</p></div><div className="chapter-list">{chapters.map((c,i)=><Link to="/hoofdstuk/$slug" params={{slug:c.slug}} className="chapter-item" key={c.slug}><span className="chapter-nr">{c.nr}</span><div><h3>{c.title}</h3><p>{c.deck}</p></div><span className="read-label">{i===0?"Begin hier":"Lees"}<ArrowRight size={16}/></span></Link>)}</div></section>
  <section className="evidence-band"><div className="section-heading"><p className="eyebrow text-alert">Bewijs boven bewering</p><h2>Elke centrale claim heeft een status.</h2></div><div className="evidence-grid">{claims.slice(0,4).map(c=><article key={c.id}><div><code>{c.id}</code><StatusBadge status={c.status}/></div><h3>{c.title}</h3><p>{c.sources.length?`${c.sources.length} gekoppelde bron${c.sources.length>1?'nen':''}`:"Geen bevestigende bron gevonden"}</p></article>)}</div><Link to="/claims" className="text-link">Bekijk alle claims <ArrowRight size={16}/></Link></section>
  <section className="publication-band"><div><p className="eyebrow">Record-versie · 19 september 2026</p><h2>Een publicatie om te lezen, niet alleen te downloaden.</h2><p>De volledig herschreven uitgave scheidt feiten van aantijgingen en open vragen. De online versie blijft leidend voor correcties.</p></div><a href={dossierAsset.url} target="_blank" rel="noreferrer" className="primary-action"><FileText size={17}/>Open de PDF</a></section>
  </main></SiteShell>}