/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoekRouteImport } from './routes/boek'
import { Route as BronnenRouteImport } from './routes/bronnen'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as DossierRouteImport } from './routes/dossier'
import { Route as MethodologieRouteImport } from './routes/methodologie'
import { Route as BoekSlugRouteImport } from './routes/boek.$slug'
import { Route as DossierSlugRouteImport } from './routes/dossier.$slug'
import { Route as HoofdstukSlugRouteImport } from './routes/hoofdstuk.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoekRoute = BoekRouteImport.update({
  id: '/boek',
  path: '/boek',
  getParentRoute: () => rootRouteImport,
} as any)
const BronnenRoute = BronnenRouteImport.update({
  id: '/bronnen',
  path: '/bronnen',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierRoute = DossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologieRoute = MethodologieRouteImport.update({
  id: '/methodologie',
  path: '/methodologie',
  getParentRoute: () => rootRouteImport,
} as any)
const BoekSlugRoute = BoekSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BoekRoute,
} as any)
const DossierSlugRoute = DossierSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DossierRoute,
} as any)
const HoofdstukSlugRoute = HoofdstukSlugRouteImport.update({
  id: '/hoofdstuk/$slug',
  path: '/hoofdstuk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boek': typeof BoekRouteWithChildren
  '/bronnen': typeof BronnenRoute
  '/claims': typeof ClaimsRoute
  '/dossier': typeof DossierRouteWithChildren
  '/methodologie': typeof MethodologieRoute
  '/boek/$slug': typeof BoekSlugRoute
  '/dossier/$slug': typeof DossierSlugRoute
  '/hoofdstuk/$slug': typeof HoofdstukSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boek': typeof BoekRouteWithChildren
  '/bronnen': typeof BronnenRoute
  '/claims': typeof ClaimsRoute
  '/dossier': typeof DossierRouteWithChildren
  '/methodologie': typeof MethodologieRoute
  '/boek/$slug': typeof BoekSlugRoute
  '/dossier/$slug': typeof DossierSlugRoute
  '/hoofdstuk/$slug': typeof HoofdstukSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boek': typeof BoekRouteWithChildren
  '/bronnen': typeof BronnenRoute
  '/claims': typeof ClaimsRoute
  '/dossier': typeof DossierRouteWithChildren
  '/methodologie': typeof MethodologieRoute
  '/boek/$slug': typeof BoekSlugRoute
  '/dossier/$slug': typeof DossierSlugRoute
  '/hoofdstuk/$slug': typeof HoofdstukSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boek'
    | '/bronnen'
    | '/claims'
    | '/dossier'
    | '/methodologie'
    | '/boek/$slug'
    | '/dossier/$slug'
    | '/hoofdstuk/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boek'
    | '/bronnen'
    | '/claims'
    | '/dossier'
    | '/methodologie'
    | '/boek/$slug'
    | '/dossier/$slug'
    | '/hoofdstuk/$slug'
  id:
    | '__root__'
    | '/'
    | '/boek'
    | '/bronnen'
    | '/claims'
    | '/dossier'
    | '/methodologie'
    | '/boek/$slug'
    | '/dossier/$slug'
    | '/hoofdstuk/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoekRoute: typeof BoekRouteWithChildren
  BronnenRoute: typeof BronnenRoute
  ClaimsRoute: typeof ClaimsRoute
  DossierRoute: typeof DossierRouteWithChildren
  MethodologieRoute: typeof MethodologieRoute
  HoofdstukSlugRoute: typeof HoofdstukSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boek': {
      id: '/boek'
      path: '/boek'
      fullPath: '/boek'
      preLoaderRoute: typeof BoekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bronnen': {
      id: '/bronnen'
      path: '/bronnen'
      fullPath: '/bronnen'
      preLoaderRoute: typeof BronnenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier': {
      id: '/dossier'
      path: '/dossier'
      fullPath: '/dossier'
      preLoaderRoute: typeof DossierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodologie': {
      id: '/methodologie'
      path: '/methodologie'
      fullPath: '/methodologie'
      preLoaderRoute: typeof MethodologieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boek/$slug': {
      id: '/boek/$slug'
      path: '/$slug'
      fullPath: '/boek/$slug'
      preLoaderRoute: typeof BoekSlugRouteImport
      parentRoute: typeof BoekRoute
    }
    '/dossier/$slug': {
      id: '/dossier/$slug'
      path: '/$slug'
      fullPath: '/dossier/$slug'
      preLoaderRoute: typeof DossierSlugRouteImport
      parentRoute: typeof DossierRoute
    }
    '/hoofdstuk/$slug': {
      id: '/hoofdstuk/$slug'
      path: '/hoofdstuk/$slug'
      fullPath: '/hoofdstuk/$slug'
      preLoaderRoute: typeof HoofdstukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BoekRouteChildren {
  BoekSlugRoute: typeof BoekSlugRoute
}

const BoekRouteChildren: BoekRouteChildren = {
  BoekSlugRoute: BoekSlugRoute,
}

const BoekRouteWithChildren = BoekRoute._addFileChildren(BoekRouteChildren)

interface DossierRouteChildren {
  DossierSlugRoute: typeof DossierSlugRoute
}

const DossierRouteChildren: DossierRouteChildren = {
  DossierSlugRoute: DossierSlugRoute,
}

const DossierRouteWithChildren =
  DossierRoute._addFileChildren(DossierRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoekRoute: BoekRouteWithChildren,
  BronnenRoute: BronnenRoute,
  ClaimsRoute: ClaimsRoute,
  DossierRoute: DossierRouteWithChildren,
  MethodologieRoute: MethodologieRoute,
  HoofdstukSlugRoute: HoofdstukSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
