/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiefRouteImport } from './routes/archief'
import { Route as BronnenRouteImport } from './routes/bronnen'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as FilosofieRouteImport } from './routes/filosofie'
import { Route as MethodologieRouteImport } from './routes/methodologie'
import { Route as OntkoppelingRouteImport } from './routes/ontkoppeling'
import { Route as BoekIndexRouteImport } from './routes/boek.index'
import { Route as BoekSlugRouteImport } from './routes/boek.$slug'
import { Route as DossierIndexRouteImport } from './routes/dossier.index'
import { Route as DossierSlugRouteImport } from './routes/dossier.$slug'
import { Route as HoofdstukSlugRouteImport } from './routes/hoofdstuk.$slug'
import { Route as JuridischIndexRouteImport } from './routes/juridisch.index'
import { Route as JuridischLexHumanitasRouteImport } from './routes/juridisch.lex-humanitas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiefRoute = ArchiefRouteImport.update({
  id: '/archief',
  path: '/archief',
  getParentRoute: () => rootRouteImport,
} as any)
const BronnenRoute = BronnenRouteImport.update({
  id: '/bronnen',
  path: '/bronnen',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const FilosofieRoute = FilosofieRouteImport.update({
  id: '/filosofie',
  path: '/filosofie',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologieRoute = MethodologieRouteImport.update({
  id: '/methodologie',
  path: '/methodologie',
  getParentRoute: () => rootRouteImport,
} as any)
const OntkoppelingRoute = OntkoppelingRouteImport.update({
  id: '/ontkoppeling',
  path: '/ontkoppeling',
  getParentRoute: () => rootRouteImport,
} as any)
const BoekIndexRoute = BoekIndexRouteImport.update({
  id: '/boek/',
  path: '/boek/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoekSlugRoute = BoekSlugRouteImport.update({
  id: '/boek/$slug',
  path: '/boek/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierIndexRoute = DossierIndexRouteImport.update({
  id: '/dossier/',
  path: '/dossier/',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierSlugRoute = DossierSlugRouteImport.update({
  id: '/dossier/$slug',
  path: '/dossier/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HoofdstukSlugRoute = HoofdstukSlugRouteImport.update({
  id: '/hoofdstuk/$slug',
  path: '/hoofdstuk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JuridischIndexRoute = JuridischIndexRouteImport.update({
  id: '/juridisch/',
  path: '/juridisch/',
  getParentRoute: () => rootRouteImport,
} as any)
const JuridischLexHumanitasRoute = JuridischLexHumanitasRouteImport.update({
  id: '/juridisch/lex-humanitas',
  path: '/juridisch/lex-humanitas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archief': typeof ArchiefRoute
  '/bronnen': typeof BronnenRoute
  '/claims': typeof ClaimsRoute
  '/filosofie': typeof FilosofieRoute
  '/methodologie': typeof MethodologieRoute
  '/ontkoppeling': typeof OntkoppelingRoute
  '/boek/$slug': typeof BoekSlugRoute
  '/dossier/$slug': typeof DossierSlugRoute
  '/hoofdstuk/$slug': typeof HoofdstukSlugRoute
  '/juridisch/lex-humanitas': typeof JuridischLexHumanitasRoute
  '/boek/': typeof BoekIndexRoute
  '/dossier/': typeof DossierIndexRoute
  '/juridisch/': typeof JuridischIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archief': typeof ArchiefRoute
  '/bronnen': typeof BronnenRoute
  '/claims': typeof ClaimsRoute
  '/filosofie': typeof FilosofieRoute
  '/methodologie': typeof MethodologieRoute
  '/ontkoppeling': typeof OntkoppelingRoute
  '/boek/$slug': typeof BoekSlugRoute
  '/dossier/$slug': typeof DossierSlugRoute
  '/hoofdstuk/$slug': typeof HoofdstukSlugRoute
  '/juridisch/lex-humanitas': typeof JuridischLexHumanitasRoute
  '/boek': typeof BoekIndexRoute
  '/dossier': typeof DossierIndexRoute
  '/juridisch': typeof JuridischIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archief': typeof ArchiefRoute
  '/bronnen': typeof BronnenRoute
  '/claims': typeof ClaimsRoute
  '/filosofie': typeof FilosofieRoute
  '/methodologie': typeof MethodologieRoute
  '/ontkoppeling': typeof OntkoppelingRoute
  '/boek/$slug': typeof BoekSlugRoute
  '/dossier/$slug': typeof DossierSlugRoute
  '/hoofdstuk/$slug': typeof HoofdstukSlugRoute
  '/juridisch/lex-humanitas': typeof JuridischLexHumanitasRoute
  '/boek/': typeof BoekIndexRoute
  '/dossier/': typeof DossierIndexRoute
  '/juridisch/': typeof JuridischIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archief'
    | '/bronnen'
    | '/claims'
    | '/filosofie'
    | '/methodologie'
    | '/ontkoppeling'
    | '/boek/$slug'
    | '/dossier/$slug'
    | '/hoofdstuk/$slug'
    | '/juridisch/lex-humanitas'
    | '/boek/'
    | '/dossier/'
    | '/juridisch/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archief'
    | '/bronnen'
    | '/claims'
    | '/filosofie'
    | '/methodologie'
    | '/ontkoppeling'
    | '/boek/$slug'
    | '/dossier/$slug'
    | '/hoofdstuk/$slug'
    | '/juridisch/lex-humanitas'
    | '/boek'
    | '/dossier'
    | '/juridisch'
  id:
    | '__root__'
    | '/'
    | '/archief'
    | '/bronnen'
    | '/claims'
    | '/filosofie'
    | '/methodologie'
    | '/ontkoppeling'
    | '/boek/$slug'
    | '/dossier/$slug'
    | '/hoofdstuk/$slug'
    | '/juridisch/lex-humanitas'
    | '/boek/'
    | '/dossier/'
    | '/juridisch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiefRoute: typeof ArchiefRoute
  BronnenRoute: typeof BronnenRoute
  ClaimsRoute: typeof ClaimsRoute
  FilosofieRoute: typeof FilosofieRoute
  MethodologieRoute: typeof MethodologieRoute
  OntkoppelingRoute: typeof OntkoppelingRoute
  BoekSlugRoute: typeof BoekSlugRoute
  DossierSlugRoute: typeof DossierSlugRoute
  HoofdstukSlugRoute: typeof HoofdstukSlugRoute
  JuridischLexHumanitasRoute: typeof JuridischLexHumanitasRoute
  BoekIndexRoute: typeof BoekIndexRoute
  DossierIndexRoute: typeof DossierIndexRoute
  JuridischIndexRoute: typeof JuridischIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archief': {
      id: '/archief'
      path: '/archief'
      fullPath: '/archief'
      preLoaderRoute: typeof ArchiefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bronnen': {
      id: '/bronnen'
      path: '/bronnen'
      fullPath: '/bronnen'
      preLoaderRoute: typeof BronnenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filosofie': {
      id: '/filosofie'
      path: '/filosofie'
      fullPath: '/filosofie'
      preLoaderRoute: typeof FilosofieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodologie': {
      id: '/methodologie'
      path: '/methodologie'
      fullPath: '/methodologie'
      preLoaderRoute: typeof MethodologieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ontkoppeling': {
      id: '/ontkoppeling'
      path: '/ontkoppeling'
      fullPath: '/ontkoppeling'
      preLoaderRoute: typeof OntkoppelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boek/': {
      id: '/boek/'
      path: '/boek'
      fullPath: '/boek/'
      preLoaderRoute: typeof BoekIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boek/$slug': {
      id: '/boek/$slug'
      path: '/boek/$slug'
      fullPath: '/boek/$slug'
      preLoaderRoute: typeof BoekSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier/': {
      id: '/dossier/'
      path: '/dossier'
      fullPath: '/dossier/'
      preLoaderRoute: typeof DossierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier/$slug': {
      id: '/dossier/$slug'
      path: '/dossier/$slug'
      fullPath: '/dossier/$slug'
      preLoaderRoute: typeof DossierSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoofdstuk/$slug': {
      id: '/hoofdstuk/$slug'
      path: '/hoofdstuk/$slug'
      fullPath: '/hoofdstuk/$slug'
      preLoaderRoute: typeof HoofdstukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juridisch/': {
      id: '/juridisch/'
      path: '/juridisch'
      fullPath: '/juridisch/'
      preLoaderRoute: typeof JuridischIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juridisch/lex-humanitas': {
      id: '/juridisch/lex-humanitas'
      path: '/juridisch/lex-humanitas'
      fullPath: '/juridisch/lex-humanitas'
      preLoaderRoute: typeof JuridischLexHumanitasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiefRoute: ArchiefRoute,
  BronnenRoute: BronnenRoute,
  ClaimsRoute: ClaimsRoute,
  FilosofieRoute: FilosofieRoute,
  MethodologieRoute: MethodologieRoute,
  OntkoppelingRoute: OntkoppelingRoute,
  BoekSlugRoute: BoekSlugRoute,
  DossierSlugRoute: DossierSlugRoute,
  HoofdstukSlugRoute: HoofdstukSlugRoute,
  JuridischLexHumanitasRoute: JuridischLexHumanitasRoute,
  BoekIndexRoute: BoekIndexRoute,
  DossierIndexRoute: DossierIndexRoute,
  JuridischIndexRoute: JuridischIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
